import {test, expect} from './fixtures.js';

// ============================================================================
// Tasks v2 T5 — System Tasks tab functional read-only.
//
// Admin sees the System Tasks tab. Inside the tab, every task_system_rules
// row renders as a collapsible card; expanding a card reveals open
// task_instances generated by that rule (matched via from_system_rule_id).
// Orphan / unknown-rule system instances appear in a dedicated bottom group.
// No edit/delete/save/generate/assign controls exist anywhere in the tab.
//
// Non-admin users still cannot see the tab — that gate already covered by
// the T2 spec, but we re-assert here so a T5 regression that quietly
// inverts the gate fails this spec on its own.
// ============================================================================

const TEST_ADMIN_EMAIL = process.env.VITE_TEST_ADMIN_EMAIL;

async function seedAdminProfile(supabaseAdmin) {
  const {data: u} = await supabaseAdmin.auth.admin.listUsers();
  const adminUser = (u && u.users ? u.users : []).find(
    (x) => (x.email || '').toLowerCase() === (TEST_ADMIN_EMAIL || '').toLowerCase(),
  );
  if (!adminUser) throw new Error('admin auth user not found in TEST DB');
  await supabaseAdmin
    .from('profiles')
    .upsert({id: adminUser.id, email: adminUser.email, full_name: 'Test Admin', role: 'admin'}, {onConflict: 'id'});
  return adminUser.id;
}

async function profileIdByName(supabaseAdmin, fullName) {
  const {data} = await supabaseAdmin.from('profiles').select('id').ilike('full_name', fullName).limit(1);
  if (!data || data.length === 0) throw new Error(`profile "${fullName}" not found in TEST DB`);
  return data[0].id;
}

async function ensureSystemRule(supabaseAdmin, ruleId, name, assigneeProfileId, generatorKind, opts = {}) {
  const {error} = await supabaseAdmin.from('task_system_rules').upsert(
    {
      id: ruleId,
      name,
      description: opts.description || `seeded for tasks_v2_t5_system_tasks: ${ruleId}`,
      assignee_profile_id: assigneeProfileId,
      generator_kind: generatorKind,
      lead_time_days: opts.lead_time_days != null ? opts.lead_time_days : 3,
      active: opts.active != null ? opts.active : true,
    },
    {onConflict: 'id'},
  );
  if (error) throw new Error(`ensureSystemRule(${ruleId}): ${error.message}`);
}

async function seedT5Fixture(supabaseAdmin) {
  const adminId = await seedAdminProfile(supabaseAdmin);
  const simonId = await profileIdByName(supabaseAdmin, 'Simon');
  const makId = await profileIdByName(supabaseAdmin, 'Mak');

  // The four built-in rules from mig 052 are already seeded in TEST.
  // We just need to ensure they exist (idempotent upsert) plus any
  // overrides (lead time / active flag) the spec wants to assert against.
  await ensureSystemRule(
    supabaseAdmin,
    'broiler-4wk-weighin',
    'Broiler 4-week weigh-in',
    simonId,
    'broiler_4wk_weighin',
  );
  await ensureSystemRule(
    supabaseAdmin,
    'broiler-6wk-weighin',
    'Broiler 6-week weigh-in',
    simonId,
    'broiler_6wk_weighin',
  );
  await ensureSystemRule(supabaseAdmin, 'clean-brooder', 'Clean brooder', simonId, 'clean_brooder', {active: false});
  await ensureSystemRule(supabaseAdmin, 'pig-6mo-weighin', 'Pig 6-month weigh-in', makId, 'pig_6mo_weighin', {
    lead_time_days: 5,
  });

  const rows = [
    // Two open broiler-4wk instances assigned to Simon — group sort.
    {
      id: 'tic-t5-b4wk-late',
      template_id: null,
      assignee_profile_id: simonId,
      due_date: '2026-06-15',
      title: 'B-26-09 4-week weigh-in',
      submission_source: 'admin_manual',
      status: 'open',
      from_system_rule_id: 'broiler-4wk-weighin',
      from_system_source_event_key: 'broiler-B-26-09',
      from_recurring_template: false,
      designation: 'system',
    },
    {
      id: 'tic-t5-b4wk-early',
      template_id: null,
      assignee_profile_id: simonId,
      due_date: '2026-05-15',
      title: 'B-26-08 4-week weigh-in',
      submission_source: 'admin_manual',
      status: 'open',
      from_system_rule_id: 'broiler-4wk-weighin',
      from_system_source_event_key: 'broiler-B-26-08',
      from_recurring_template: false,
      designation: 'system',
    },
    // One pig-6mo instance under Mak.
    {
      id: 'tic-t5-pig6mo',
      template_id: null,
      assignee_profile_id: makId,
      due_date: '2026-09-01',
      title: 'P-26-01-A 6-month weigh-in',
      submission_source: 'admin_manual',
      status: 'open',
      from_system_rule_id: 'pig-6mo-weighin',
      from_system_source_event_key: 'pig-P-26-01-A',
      from_recurring_template: false,
      designation: 'system',
    },
    // Orphan — designation='system' but from_system_rule_id points at a
    // rule that isn't in task_system_rules. Owning rule was deleted.
    {
      id: 'tic-t5-orphan-unknown',
      template_id: null,
      assignee_profile_id: simonId,
      due_date: '2026-05-20',
      title: 'Orphan unknown-rule system task',
      submission_source: 'admin_manual',
      status: 'open',
      from_system_rule_id: 'rule-deleted-long-ago',
      from_recurring_template: false,
      designation: 'system',
    },
  ];

  const {error} = await supabaseAdmin.from('task_instances').upsert(rows, {onConflict: 'id'});
  if (error) throw new Error(`seedT5Fixture: ${error.message}`);
  return {adminId, simonId, makId};
}

test.describe('Tasks v2 T5 — System Tasks tab', () => {
  test('admin sees the System Tasks tab and the seeded rules', async ({page, supabaseAdmin, resetDb}) => {
    await resetDb();
    await seedT5Fixture(supabaseAdmin);

    await page.goto('/tasks');
    await page.locator('[data-tasks-tab-button="system"]').click();

    const tab = page.locator('[data-tasks-tab="system"]');
    await expect(tab).toBeVisible();

    // Active rules render directly under the Active rules sub-section.
    await expect(tab.locator('[data-system-rule="broiler-4wk-weighin"]')).toBeVisible();
    await expect(tab.locator('[data-system-rule="broiler-6wk-weighin"]')).toBeVisible();
    await expect(tab.locator('[data-system-rule="pig-6mo-weighin"]')).toBeVisible();

    // clean-brooder is seeded inactive in this fixture. Under the Codex
    // 2026-05-13 remaining-tabs pass, inactive rules sit behind a
    // collapsible Inactive rules toggle (collapsed by default); expand
    // it once so the card is in the DOM.
    await tab.locator('[data-system-inactive-toggle="1"]').click();
    await expect(tab.locator('[data-system-rule="clean-brooder"]')).toBeVisible();

    // Active/inactive pills surface correctly.
    await expect(tab.locator('[data-system-rule="broiler-4wk-weighin"] [data-rule-state="active"]')).toBeVisible();
    await expect(tab.locator('[data-system-rule="clean-brooder"] [data-rule-state="inactive"]')).toBeVisible();

    // Generator-kind label is visible on each card.
    await expect(
      tab.locator('[data-system-rule="broiler-4wk-weighin"] [data-rule-generator-kind="broiler_4wk_weighin"]'),
    ).toBeVisible();
    await expect(
      tab.locator('[data-system-rule="pig-6mo-weighin"] [data-rule-generator-kind="pig_6mo_weighin"]'),
    ).toBeVisible();

    // Lead-time days on the pig rule was overridden to 5 by the seed.
    await expect(tab.locator('[data-system-rule="pig-6mo-weighin"] [data-rule-lead-time-days]')).toHaveAttribute(
      'data-rule-lead-time-days',
      '5',
    );
  });

  test('open system instances group under their rules and sort due_date ascending on expand', async ({
    page,
    supabaseAdmin,
    resetDb,
  }) => {
    await resetDb();
    await seedT5Fixture(supabaseAdmin);

    await page.goto('/tasks');
    await page.locator('[data-tasks-tab-button="system"]').click();
    const tab = page.locator('[data-tasks-tab="system"]');

    // Open count surfaces on the rule header.
    await expect(tab.locator('[data-system-rule="broiler-4wk-weighin"] [data-rule-open-count]')).toHaveAttribute(
      'data-rule-open-count',
      '2',
    );
    await expect(tab.locator('[data-system-rule="pig-6mo-weighin"] [data-rule-open-count]')).toHaveAttribute(
      'data-rule-open-count',
      '1',
    );
    await expect(tab.locator('[data-system-rule="broiler-6wk-weighin"] [data-rule-open-count]')).toHaveAttribute(
      'data-rule-open-count',
      '0',
    );

    // Bodies start collapsed.
    await expect(tab.locator('[data-system-rule-body="broiler-4wk-weighin"]')).toHaveCount(0);

    // Expand broiler-4wk → both instances appear in due_date ascending order.
    await tab.locator('[data-system-rule="broiler-4wk-weighin"] button').first().click();
    const broilerBody = tab.locator('[data-system-rule-body="broiler-4wk-weighin"]');
    await expect(broilerBody).toBeVisible();
    const ids = await broilerBody.locator('[data-task-row]').evaluateAll((els) => els.map((e) => e.dataset.taskRow));
    expect(ids).toEqual(['tic-t5-b4wk-early', 'tic-t5-b4wk-late']);

    // Source-event-key surfaces on each instance row.
    await expect(broilerBody.locator('[data-source-event-key="broiler-B-26-08"]')).toBeVisible();
    await expect(broilerBody.locator('[data-source-event-key="broiler-B-26-09"]')).toBeVisible();
  });

  test('orphan / unknown-rule system tasks appear at the bottom', async ({page, supabaseAdmin, resetDb}) => {
    await resetDb();
    await seedT5Fixture(supabaseAdmin);

    await page.goto('/tasks');
    await page.locator('[data-tasks-tab-button="system"]').click();
    const tab = page.locator('[data-tasks-tab="system"]');

    const orphans = tab.locator('[data-system-orphans="1"]');
    await expect(orphans).toBeVisible();
    await expect(orphans.locator('[data-task-row="tic-t5-orphan-unknown"]')).toBeVisible();

    // The orphaned row is NOT under any of the rule cards.
    await expect(
      tab.locator('[data-system-rule="broiler-4wk-weighin"] [data-task-row="tic-t5-orphan-unknown"]'),
    ).toHaveCount(0);
    await expect(
      tab.locator('[data-system-rule="pig-6mo-weighin"] [data-task-row="tic-t5-orphan-unknown"]'),
    ).toHaveCount(0);
  });

  test('admin sees only the Edit Rule control (no generate/assign/delete/save) inside the tab body', async ({
    page,
    supabaseAdmin,
    resetDb,
  }) => {
    await resetDb();
    await seedT5Fixture(supabaseAdmin);

    await page.goto('/tasks');
    await page.locator('[data-tasks-tab-button="system"]').click();
    const tab = page.locator('[data-tasks-tab="system"]');
    await expect(tab).toBeVisible();

    // Expand a rule so any per-instance controls would also render.
    await tab.locator('[data-system-rule="broiler-4wk-weighin"] button').first().click();

    // T9 added an admin Edit Rule button. The other forbidden controls
    // (Save/Generate/Delete/Assign) must NOT appear at the tab level —
    // they only show up inside the rule edit modal once admin clicks
    // Edit Rule. Until then the tab body stays inspect-only, with ONE
    // sanctioned exception: the orphan section's per-instance
    // "Delete orphan" cleanup button (the fixture seeds an orphan row).
    await expect(tab.locator('[data-system-rule-edit-button="broiler-4wk-weighin"]')).toBeVisible();
    // The fixture seeds exactly ONE orphan, so exactly ONE delete control
    // exists in the whole tab — the orphan section's sanctioned per-instance
    // cleanup button — and no rule card ever hosts a delete control.
    const deleteButtons = tab.getByRole('button', {name: /^delete/i});
    await expect(deleteButtons).toHaveCount(1);
    await expect(deleteButtons.first()).toHaveAttribute('data-system-orphan-delete-button', /.+/);
    await expect(tab.locator('[data-system-rule] button', {hasText: /^delete/i})).toHaveCount(0);
    await expect(tab.getByRole('button', {name: /^save/i})).toHaveCount(0);
    await expect(tab.getByRole('button', {name: /^generate/i})).toHaveCount(0);
    await expect(tab.getByRole('button', {name: /^assign/i})).toHaveCount(0);
    await expect(tab.locator('input')).toHaveCount(0);
    await expect(tab.locator('textarea')).toHaveCount(0);
    await expect(tab.locator('select')).toHaveCount(0);
  });

  test('non-admin (farm_team) signed-in user can reach /tasks but cannot see the System Tasks tab', async ({
    page,
    supabaseAdmin,
    resetDb,
  }) => {
    await resetDb();
    await seedT5Fixture(supabaseAdmin);

    await page.context().clearCookies();
    await page.goto('/');
    await page.evaluate(() => {
      try {
        localStorage.clear();
        sessionStorage.clear();
      } catch (_e) {
        /* test-only cleanup; ignore browser quirks */
      }
    });
    await page.goto('/');
    await page.getByPlaceholder('your@email.com').first().fill('simon.tasks@wcfplanner.test');
    await page.getByPlaceholder('••••••••').fill('apply_test_mig_052_placeholder_password');
    await page.getByRole('button', {name: /^sign in$/i}).click();
    await expect(page.locator('[data-login-screen]')).toHaveCount(0, {timeout: 15_000});
    // Wait out the app's fail-closed cold-boot data load BEFORE navigating —
    // the /tasks assertions otherwise race the farm-data fetch on a fresh
    // (storage-cleared) session and burn the test budget on the boot screen.
    await expect(page.getByText('Loading your farm data...')).toHaveCount(0, {timeout: 15_000});

    await page.goto('/tasks');

    await expect(page.getByRole('heading', {name: /^Task Center$/})).toBeVisible();
    await expect(page.locator('[data-tasks-tab-button="mine"]')).toBeVisible();
    await expect(page.locator('[data-tasks-tab-button="recurring"]')).toBeVisible();
    await expect(page.locator('[data-tasks-tab-button="completed"]')).toBeVisible();
    // System Tasks tab gated to admin.
    await expect(page.locator('[data-tasks-tab-button="system"]')).toHaveCount(0);
    // And the body of the system tab is not in the DOM either, even
    // though we cannot click an absent tab button.
    await expect(page.locator('[data-tasks-tab="system"]')).toHaveCount(0);
  });
});
