-- ============================================================================
-- 180_pasture_direct_rest_history.sql
-- Pasture Map: direct moves own occupancy and the rest/history clock.
--
-- Root defect:
--   pasture_move_impacts intentionally records geometric overlaps so the map
--   can explain boundary conflicts. _land_area_summary also treated those
--   advisory rows as real grazing. That produced two user-visible failures:
--
--   * a current overlap made a resting paddock "Occupied", reset rest_days to
--     zero, and removed its resting fill even though the herd lived elsewhere;
--   * a later overlap-derived departure replaced the paddock's real move-out
--     timestamp, so "Rest started" disagreed with the direct stay timeline.
--
-- Contract after this migration:
--   * only a latest move whose to_land_area_id = the area is occupancy;
--   * only a move whose from_land_area_id = the area starts/restarts rest;
--   * last_touched_at is the latest DIRECT arrival/departure, so "Last grazed"
--     agrees with the completed stay's exit;
--   * overlap occupants remain in current_occupants as advisory information,
--     but never affect current_occupancy_count, rest_state, or rest_days;
--   * the existing 60-day ready threshold is unchanged.
--
-- No table/data/RLS/grant change. Existing impacts are retained and become
-- inert for authoritative state immediately on read.
-- ============================================================================

-- Occupancy-sensitive archive/delete helpers must use the same direct-location
-- rule as the map summary. A geometric neighbour must never block an operation
-- merely because it carries an overlap impact.
CREATE OR REPLACE FUNCTION public._land_area_is_occupied(p_id text)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, extensions
STABLE
AS $fn$
  WITH latest AS (
    SELECT DISTINCT ON (m.animal_type, m.group_key) m.*
      FROM public.pasture_move_events m
     ORDER BY m.animal_type, m.group_key, m.moved_at DESC, m.created_at DESC
  )
  SELECT EXISTS (
    SELECT 1
      FROM latest l
     WHERE l.to_land_area_id = p_id
  );
$fn$;
REVOKE ALL ON FUNCTION public._land_area_is_occupied(text) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public._land_area_summary(p_id text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
STABLE
AS $fn$
DECLARE
  v_out jsonb;
  v_current jsonb;
  v_current_count int := 0;
  v_last_departure timestamptz;
  v_last_touch timestamptz;
  v_baseline boolean := true;
  v_rest_days int;
  v_rest_state text;
BEGIN
  -- Keep destination + meaningful-overlap occupants in the payload so the UI
  -- can explain boundary overlap. This list is informational; the separate
  -- direct count below is the sole occupancy authority.
  WITH latest AS (
    SELECT DISTINCT ON (m.animal_type, m.group_key) m.*
      FROM public.pasture_move_events m
     ORDER BY m.animal_type, m.group_key, m.moved_at DESC, m.created_at DESC
  )
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'move_id', l.id,
           'animal_type', l.animal_type,
           'group_key', l.group_key,
           'group_label', l.group_label,
           'moved_at', l.moved_at,
           'animal_count', l.animal_count,
           'impact_kind', i.impact_kind
         ) ORDER BY l.animal_type, l.group_label), '[]'::jsonb)
    INTO v_current
    FROM latest l
    JOIN public.pasture_move_impacts i
      ON i.move_id = l.id
     AND i.land_area_id = p_id
     AND i.impact_kind IN ('destination', 'overlap')
     AND l.to_land_area_id IS NOT NULL
     -- A departure from this same area wins over an overlap generated by the
     -- destination of that move.
     AND NOT (
       i.impact_kind = 'overlap'
       AND EXISTS (
         SELECT 1
           FROM public.pasture_move_impacts d
          WHERE d.move_id = i.move_id
            AND d.land_area_id = i.land_area_id
            AND d.impact_kind = 'departure'
       )
     )
     -- Preserve parent/child suppression: a child destination's overlap is not
     -- useful advisory occupancy on its direct parent pasture.
     AND NOT (
       i.impact_kind = 'overlap'
       AND EXISTS (
         SELECT 1 FROM public.land_areas c
          WHERE c.id = l.to_land_area_id
            AND c.parent_id = p_id
       )
     )
     AND (
       i.impact_kind = 'destination'
       OR public._pasture_areas_overlap(p_id, l.to_land_area_id)
     );

  -- Direct current destinations only. Overlap rows above remain explanatory
  -- but cannot reset a neighbour's rest clock or paint it occupied.
  WITH latest AS (
    SELECT DISTINCT ON (m.animal_type, m.group_key) m.*
      FROM public.pasture_move_events m
     ORDER BY m.animal_type, m.group_key, m.moved_at DESC, m.created_at DESC
  )
  SELECT count(*)::int
    INTO v_current_count
    FROM latest l
   WHERE l.to_land_area_id = p_id;

  -- A paddock starts resting only when a group directly leaves it. Advisory
  -- overlap/departure impacts from a different paddock are never stays and
  -- therefore cannot advance this timestamp.
  SELECT max(m.moved_at)
    INTO v_last_departure
    FROM public.pasture_move_events m
   WHERE m.from_land_area_id = p_id;

  -- Latest direct grazing activity. For a completed stay the departure is
  -- later than its arrival, making "Last grazed" equal the stay's actual end.
  SELECT max(m.moved_at)
    INTO v_last_touch
    FROM public.pasture_move_events m
   WHERE m.from_land_area_id = p_id
      OR m.to_land_area_id = p_id;

  SELECT baseline_no_history
    INTO v_baseline
    FROM public.land_areas
   WHERE id = p_id;

  IF v_current_count > 0 THEN
    v_rest_days := 0;
    v_rest_state := 'occupied';
  ELSIF v_last_departure IS NOT NULL THEN
    v_rest_days := floor(extract(epoch from (now() - v_last_departure)) / 86400)::int;
    v_rest_state := CASE WHEN v_rest_days < 60 THEN 'resting' ELSE 'rested' END;
  ELSIF COALESCE(v_baseline, true)
        OR (v_last_touch IS NULL AND v_last_departure IS NULL) THEN
    v_rest_days := NULL;
    v_rest_state := 'baseline';
  ELSE
    v_rest_days := NULL;
    v_rest_state := 'no_history';
  END IF;

  SELECT jsonb_build_object(
    'id', a.id,
    'parent_id', a.parent_id,
    'kind', a.kind,
    'name', a.name,
    'permanence', a.permanence,
    'designation', a.designation,
    'status', a.status,
    'review_status', a.review_status,
    'geometry_status', a.geometry_status,
    'baseline_no_history', a.baseline_no_history,
    'manual_acres', a.manual_acres,
    'computed_acres', a.computed_acres,
    'effective_acres', COALESCE(a.manual_acres, a.computed_acres),
    'source', a.source,
    'source_external_id', a.source_external_id,
    'import_batch_id', a.import_batch_id,
    'raw_name', a.raw_name,
    'raw_notes', a.raw_notes,
    'raw_color', a.raw_color,
    'line_color', a.line_color,
    'line_weight', a.line_weight,
    'line_pattern', a.line_pattern,
    'created_at', a.created_at,
    'updated_at', a.updated_at,
    'child_count', (SELECT count(*) FROM public.land_areas c
                     WHERE c.parent_id = a.id AND c.deleted_at IS NULL),
    'raw_geometry', CASE WHEN a.raw_geometry IS NULL THEN NULL
                         ELSE extensions.ST_AsGeoJSON(a.raw_geometry)::jsonb END,
    'current_version', (
      SELECT jsonb_build_object(
        'id', v.id,
        'version_number', v.version_number,
        'computed_acres', v.computed_acres,
        'created_at', v.created_at,
        'geometry', extensions.ST_AsGeoJSON(v.geom)::jsonb)
      FROM public.land_area_geometry_versions v
      WHERE v.land_area_id = a.id
      ORDER BY v.version_number DESC
      LIMIT 1
    ),
    'current_occupants', v_current,
    'current_occupancy_count', v_current_count,
    'last_touched_at', v_last_touch,
    'last_moved_out_at', v_last_departure,
    'rest_days', v_rest_days,
    'rest_state', v_rest_state
  )
  INTO v_out
  FROM public.land_areas a
  WHERE a.id = p_id;

  RETURN v_out;
END
$fn$;
REVOKE ALL ON FUNCTION public._land_area_summary(text) FROM PUBLIC, anon, authenticated;

NOTIFY pgrst, 'reload schema';

