// Task Center — System Tasks tab. Admin-only. Tasks v2.
//
// Lists task_system_rules as collapsible cards. Each card shows the
// rule id/name, description, generator-kind label, assignee, lead-time
// days, active/inactive pill, open-instance count, and (Codex 2026-05-13
// remaining-tabs pass) a per-rule overdue badge when ≥1 of the open
// instances is past due. Expanding a card reveals the open
// task_instances generated by that rule (matched via
// from_system_rule_id; designation='system' or from_system_rule_id IS
// NOT NULL). Orphan / unknown-rule instances are grouped at the bottom
// under "Orphaned system tasks".
//
// Layout sub-sections (remaining-tabs pass):
//
//   Active rules (N): rules with active=true.
//   Inactive rules (N): rules with active=false. Whole sub-section
//                       collapses by default behind a toggle so the
//                       admin view defaults to scanning the live
//                       generators. Per-rule expand stays manual on
//                       both sub-sections — no auto-expand here (the
//                       T5 spec asserts default-collapsed bodies and
//                       the system surface is a config view, not a
//                       work-queue scan).
//
// Tab visibility is gated in TaskCenterView (admin only); inside the
// tab body, the per-rule Edit Rule button (T9) is also gated by
// isAdmin as a defensive double-check.
//
// Editable surface (T9): admin can update assignee_profile_id,
// lead_time_days, and active via SystemRuleEditModal. id /
// generator_kind / name / description stay read-only — the Edge
// Function dispatcher recognizes only the four built-in
// generator_kinds, so renaming or rekeying would silently break
// generation. T9 explicitly excludes creating or deleting system
// rules; only the four built-in rules from mig 052 exist. The
// frontend never calls the system-rule generator RPC — that path
// stays owned by the cron Edge Function.

import React from 'react';
import {
  loadSystemTaskRules,
  loadOpenSystemTaskInstances,
  loadEligibleProfilesById,
  loadTaskAssignableProfilesById,
  groupSystemTasksByRule,
  dueStateFor,
} from '../lib/tasksCenterApi.js';
import {TASK_CHANGE_EVENT, fireTaskChangeEvent} from '../lib/tasksCenterMutationsApi.js';
import {fmt, todayCentralISO} from '../lib/dateUtils.js';
import SystemRuleEditModal from './SystemRuleEditModal.jsx';
import DeleteTaskModal from './DeleteTaskModal.jsx';

const CARD = {
  background: 'white',
  borderRadius: 10,
  padding: '12px 14px',
  marginBottom: 10,
  boxShadow: '0 1px 3px rgba(0,0,0,.06)',
  border: '1px solid var(--border)',
};
const SUB = {fontSize: 12, color: 'var(--ink-muted)'};
const SECTION_HEADER = {
  fontSize: 13,
  fontWeight: 700,
  color: 'var(--ink)',
  margin: '14px 0 8px',
  textTransform: 'uppercase',
  letterSpacing: 0.4,
};
const SUBSECTION_HEADER = {
  fontSize: 12,
  fontWeight: 700,
  color: 'var(--ink-muted)',
  margin: '10px 0 6px',
  textTransform: 'uppercase',
  letterSpacing: 0.5,
  display: 'flex',
  alignItems: 'center',
  gap: 8,
};
const SUBSECTION_DOT_ACTIVE = {
  display: 'inline-block',
  width: 8,
  height: 8,
  borderRadius: '50%',
  background: '#10b981',
};
const INACTIVE_TOGGLE_BTN = {
  width: '100%',
  display: 'flex',
  alignItems: 'center',
  gap: 8,
  padding: '9px 10px',
  borderRadius: 10,
  border: '1px solid var(--border)',
  background: 'var(--surface-2)',
  color: 'var(--ink)',
  cursor: 'pointer',
  fontFamily: 'inherit',
  fontSize: 12,
  fontWeight: 700,
  textAlign: 'left',
  marginTop: 6,
  marginBottom: 6,
};
const LOAD_RETRY_BTN = {
  padding: '6px 12px',
  borderRadius: 10,
  border: '1px solid #991b1b',
  background: 'white',
  color: '#991b1b',
  cursor: 'pointer',
  fontSize: 12,
  fontWeight: 600,
  fontFamily: 'inherit',
  marginBottom: 12,
};
const ORPHAN_DELETE_BTN = {
  padding: '4px 10px',
  borderRadius: 10,
  border: '1px solid #991b1b',
  background: 'white',
  color: '#991b1b',
  cursor: 'pointer',
  fontSize: 12,
  fontWeight: 600,
  fontFamily: 'inherit',
};
const GROUP_HEADER = {
  background: 'white',
  border: '1px solid var(--border)',
  borderRadius: 10,
  padding: '8px 12px',
  marginBottom: 8,
  cursor: 'pointer',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  fontFamily: 'inherit',
  width: '100%',
  textAlign: 'left',
};
const PILL_BASE = {
  display: 'inline-block',
  padding: '2px 8px',
  borderRadius: 999,
  fontSize: 11,
  fontWeight: 600,
  marginLeft: 6,
};
const PILL_ACTIVE = {...PILL_BASE, background: '#ecfdf5', color: '#047857'};
const PILL_INACTIVE = {...PILL_BASE, background: '#f3f4f6', color: '#374151'};
const PILL_OVERDUE_HEADER = {...PILL_BASE, background: '#fef2f2', color: '#991b1b'};
const BADGE_OVERDUE = {
  display: 'inline-block',
  padding: '2px 8px',
  borderRadius: 999,
  fontSize: 11,
  fontWeight: 600,
  background: '#fef2f2',
  color: '#991b1b',
};
const BADGE_TODAY = {
  display: 'inline-block',
  padding: '2px 8px',
  borderRadius: 999,
  fontSize: 11,
  fontWeight: 600,
  background: '#fffbeb',
  color: '#92400e',
};

const GENERATOR_KIND_LABELS = {
  broiler_4wk_weighin: 'Broiler 4-week weigh-in',
  broiler_6wk_weighin: 'Broiler 6-week weigh-in',
  clean_brooder: 'Clean brooder',
  pig_6mo_weighin: 'Pig 6-month weigh-in',
};

function nameFor(profileId, profilesById) {
  if (!profileId) return null;
  const p = profilesById[profileId];
  return p && p.full_name ? p.full_name : 'Unknown user';
}

function generatorLabel(rule) {
  if (!rule) return '';
  return GENERATOR_KIND_LABELS[rule.generator_kind] || rule.generator_kind || '';
}

function leadTimeLabel(rule) {
  if (!rule) return '';
  const n = Number(rule.lead_time_days);
  if (!Number.isFinite(n)) return '';
  if (n === 0) return 'No lead';
  return n === 1 ? '1 day lead' : `${n} day lead`;
}

function overdueCountFor(instances, todayStr) {
  if (!Array.isArray(instances)) return 0;
  let n = 0;
  for (const ti of instances) {
    if (dueStateFor(ti, todayStr) === 'overdue') n += 1;
  }
  return n;
}

// eslint-disable-next-line no-unused-vars -- referenced via JSX <SystemInstanceLine .../> below
function SystemInstanceLine({ti, todayStr, profilesById, onDelete}) {
  const due = dueStateFor(ti, todayStr);
  const assigneeName = nameFor(ti.assignee_profile_id, profilesById);
  return (
    <div
      data-task-row={ti.id}
      data-task-designation={ti.designation || ''}
      style={{
        background: 'var(--surface-2)',
        border: '1px solid var(--border)',
        borderRadius: 10,
        padding: '8px 12px',
        marginBottom: 6,
      }}
    >
      <div
        style={{display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', gap: 10, flexWrap: 'wrap'}}
      >
        <div style={{fontSize: 13, color: 'var(--ink)', fontWeight: 500, flex: '1 1 200px', minWidth: 0}}>
          {ti.title}
        </div>
        <div style={{...SUB, whiteSpace: 'nowrap', display: 'flex', alignItems: 'center', gap: 6}}>
          {due === 'overdue' && (
            <span data-due-state="overdue" style={BADGE_OVERDUE}>
              Overdue
            </span>
          )}
          {due === 'today' && (
            <span data-due-state="today" style={BADGE_TODAY}>
              Due today
            </span>
          )}
          <span data-due-date={ti.due_date}>{fmt(ti.due_date)}</span>
          {onDelete && (
            <button
              type="button"
              data-system-orphan-delete-button={ti.id}
              onClick={() => onDelete(ti)}
              style={ORPHAN_DELETE_BTN}
            >
              Delete orphan
            </button>
          )}
        </div>
      </div>
      <div style={{...SUB, marginTop: 4}}>
        {assigneeName && (
          <>
            Assigned to <span style={{color: 'var(--ink)'}}>{assigneeName}</span>
          </>
        )}
        {ti.from_system_source_event_key && (
          <>
            {assigneeName ? ' · ' : ''}
            Source event{' '}
            <span data-source-event-key={ti.from_system_source_event_key} style={{color: 'var(--ink)'}}>
              {ti.from_system_source_event_key}
            </span>
          </>
        )}
      </div>
    </div>
  );
}

export default function SystemTasksTab({sb, authState}) {
  const isAdmin = authState && authState.role === 'admin';
  const [rules, setRules] = React.useState([]);
  const [openInstances, setOpenInstances] = React.useState([]);
  const [profiles, setProfiles] = React.useState({});
  const [assignableProfiles, setAssignableProfiles] = React.useState({});
  const [loading, setLoading] = React.useState(true);
  const [err, setErr] = React.useState('');
  const [expanded, setExpanded] = React.useState({});
  // Inactive sub-section collapsed by default — admin scans the live
  // generators first; inactive rules surface behind a toggle.
  const [showInactive, setShowInactive] = React.useState(false);
  const [editRule, setEditRule] = React.useState(null);
  const [deleteOrphanTask, setDeleteOrphanTask] = React.useState(null);
  const [reloadKey, setReloadKey] = React.useState(0);

  React.useEffect(() => {
    let cancelled = false;
    (async () => {
      setErr('');
      setLoading(true);
      try {
        const [r, opens, profMap, assignableMap] = await Promise.all([
          loadSystemTaskRules(sb),
          loadOpenSystemTaskInstances(sb),
          loadEligibleProfilesById(sb),
          loadTaskAssignableProfilesById(sb),
        ]);
        if (!cancelled) {
          setRules(r);
          setOpenInstances(opens);
          setProfiles(profMap);
          setAssignableProfiles(assignableMap);
        }
      } catch (e) {
        if (!cancelled) {
          setRules([]);
          setOpenInstances([]);
          setProfiles({});
          setAssignableProfiles({});
          setExpanded({});
          setShowInactive(false);
          setErr(e && e.message ? e.message : String(e));
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [sb, reloadKey]);

  React.useEffect(() => {
    function onChange() {
      setReloadKey((k) => k + 1);
    }
    if (typeof window !== 'undefined' && window.addEventListener) {
      window.addEventListener(TASK_CHANGE_EVENT, onChange);
    }
    return () => {
      if (typeof window !== 'undefined' && window.removeEventListener) {
        window.removeEventListener(TASK_CHANGE_EVENT, onChange);
      }
    };
  }, []);

  const todayStr = todayCentralISO();
  const loadFailed = !!err;
  const grouped = groupSystemTasksByRule(rules, openInstances);
  const activeBuckets = grouped.rules.filter((b) => b.rule.active);
  const inactiveBuckets = grouped.rules.filter((b) => !b.rule.active);

  function toggle(key) {
    setExpanded((prev) => ({...prev, [key]: !prev[key]}));
  }
  function startEditRule(r) {
    setEditRule(r);
  }

  function renderRuleCard(b) {
    const key = b.rule.id;
    const isOpen = !!expanded[key];
    const assigneeName = nameFor(b.rule.assignee_profile_id, profiles);
    const overdueCount = overdueCountFor(b.instances, todayStr);
    return (
      <div key={key} data-system-rule={key}>
        <button type="button" onClick={() => toggle(key)} style={GROUP_HEADER}>
          <div style={{display: 'flex', flexDirection: 'column', gap: 2, flex: 1, minWidth: 0}}>
            <div style={{fontSize: 14, fontWeight: 600, color: 'var(--ink)', wordBreak: 'break-word'}}>
              {b.rule.name}
              <span style={{...SUB, marginLeft: 6, fontWeight: 500}}>({b.rule.id})</span>
              {b.rule.active ? (
                <span data-rule-state="active" style={PILL_ACTIVE}>
                  Active
                </span>
              ) : (
                <span data-rule-state="inactive" style={PILL_INACTIVE}>
                  Inactive
                </span>
              )}
              {overdueCount > 0 && (
                <span data-rule-overdue-count={overdueCount} style={PILL_OVERDUE_HEADER}>
                  {overdueCount} overdue
                </span>
              )}
            </div>
            <div style={SUB}>
              <span data-rule-generator-kind={b.rule.generator_kind}>{generatorLabel(b.rule)}</span>
              {assigneeName && <> · {assigneeName}</>}
              {' · '}
              <span data-rule-lead-time-days={b.rule.lead_time_days}>{leadTimeLabel(b.rule)}</span>
              {' · '}
              <span data-rule-open-count={b.openCount}>{b.openCount}</span> open
            </div>
            {b.rule.description && (
              <div style={{...SUB, marginTop: 2, color: 'var(--ink-muted)'}}>{b.rule.description}</div>
            )}
          </div>
          <span
            data-tasks-group-state={isOpen ? 'expanded' : 'collapsed'}
            style={{fontSize: 13, color: 'var(--ink-muted)', marginLeft: 8}}
          >
            {isOpen ? '▾' : '▸'}
          </span>
        </button>
        {isOpen && (
          <div data-system-rule-body={key} style={{paddingLeft: 8, marginBottom: 8}}>
            {isAdmin && (
              <div style={{display: 'flex', gap: 6, padding: '4px 8px 8px'}}>
                <button
                  type="button"
                  data-system-rule-edit-button={key}
                  onClick={() => startEditRule(b.rule)}
                  style={{
                    padding: '4px 10px',
                    borderRadius: 10,
                    border: '1px solid var(--border-strong)',
                    background: 'white',
                    color: 'var(--ink)',
                    cursor: 'pointer',
                    fontSize: 12,
                    fontWeight: 500,
                    fontFamily: 'inherit',
                  }}
                >
                  Edit Rule
                </button>
              </div>
            )}
            {b.instances.length === 0 ? (
              <div style={{...SUB, padding: '4px 8px'}}>No open instances.</div>
            ) : (
              b.instances.map((ti) => (
                <SystemInstanceLine key={ti.id} ti={ti} todayStr={todayStr} profilesById={profiles} />
              ))
            )}
          </div>
        )}
      </div>
    );
  }

  return (
    <div data-tasks-tab="system" data-tasks-system-loaded={loading || loadFailed ? 'false' : 'true'}>
      {loadFailed && (
        <div
          data-tasks-error="1"
          style={{
            background: '#fef2f2',
            border: '1px solid #fecaca',
            color: '#991b1b',
            padding: '8px 12px',
            borderRadius: 10,
            marginBottom: 12,
            fontSize: 13,
          }}
        >
          {err}
        </div>
      )}
      {loadFailed && (
        <button
          type="button"
          data-tasks-load-retry="system"
          onClick={() => setReloadKey((k) => k + 1)}
          style={LOAD_RETRY_BTN}
        >
          Retry
        </button>
      )}
      {loading ? (
        <div style={SUB}>Loading…</div>
      ) : loadFailed ? null : (
        <>
          <div style={SECTION_HEADER}>System rules ({grouped.rules.length})</div>
          {grouped.rules.length === 0 ? (
            <div style={CARD}>
              <div style={{fontSize: 13, color: 'var(--ink)'}}>No system rules configured.</div>
            </div>
          ) : (
            <>
              <div data-system-section="active">
                <div style={SUBSECTION_HEADER}>
                  <span style={SUBSECTION_DOT_ACTIVE} aria-hidden="true" />
                  Active rules ({activeBuckets.length})
                </div>
                {activeBuckets.length === 0 ? (
                  <div style={CARD}>
                    <div style={{fontSize: 13, color: 'var(--ink)'}}>No active rules.</div>
                  </div>
                ) : (
                  activeBuckets.map(renderRuleCard)
                )}
              </div>

              {inactiveBuckets.length > 0 && (
                <div data-system-section="inactive">
                  <button
                    type="button"
                    data-system-inactive-toggle="1"
                    data-system-inactive-state={showInactive ? 'expanded' : 'collapsed'}
                    onClick={() => setShowInactive((v) => !v)}
                    style={INACTIVE_TOGGLE_BTN}
                  >
                    <span style={{fontSize: 13, color: 'var(--ink-muted)'}}>{showInactive ? '▾' : '▸'}</span>
                    Inactive rules ({inactiveBuckets.length})
                  </button>
                  {showInactive && <div style={{marginTop: 8}}>{inactiveBuckets.map(renderRuleCard)}</div>}
                </div>
              )}
            </>
          )}

          {grouped.orphans.length > 0 && (
            <div data-system-orphans="1" style={{marginTop: 18}}>
              <div style={SECTION_HEADER}>Orphaned system tasks ({grouped.orphans.length})</div>
              <div style={CARD}>
                <div style={{...SUB, marginBottom: 8}}>
                  These instances are tagged as system tasks but their owning rule was deleted or is no longer
                  available.
                </div>
                {grouped.orphans.map((ti) => (
                  <SystemInstanceLine
                    key={ti.id}
                    ti={ti}
                    todayStr={todayStr}
                    profilesById={profiles}
                    onDelete={isAdmin ? setDeleteOrphanTask : null}
                  />
                ))}
              </div>
            </div>
          )}
        </>
      )}

      {React.createElement(SystemRuleEditModal, {
        sb,
        isOpen: !!editRule,
        rule: editRule,
        // System rule assignee dropdown uses the filtered map.
        profilesById: assignableProfiles,
        onClose: () => setEditRule(null),
        onSaved: () => {
          setEditRule(null);
          fireTaskChangeEvent();
          setReloadKey((k) => k + 1);
        },
      })}
      {React.createElement(DeleteTaskModal, {
        sb,
        task: deleteOrphanTask,
        isOpen: !!deleteOrphanTask,
        onClose: () => setDeleteOrphanTask(null),
        onDeleted: () => {
          setDeleteOrphanTask(null);
          fireTaskChangeEvent();
          setReloadKey((k) => k + 1);
        },
      })}
    </div>
  );
}
