#!/usr/bin/env node
// ============================================================================
// build_test_bootstrap.js
// ============================================================================
// Concatenates every production migration (001-029) plus a test-only exec_sql
// helper into a single ordered SQL bundle at scripts/test-bootstrap.sql.
//
// Use case: bootstrap a fresh Supabase TEST project in one paste-and-run from
// the SQL Editor instead of 30 manual paste-and-runs. Output is gitignored
// since it's rebuildable; this script is the source of truth.
//
// Usage:
//   node scripts/build_test_bootstrap.js
//
// WARNING: the exec_sql function appended to the output is for the TEST
// project only. NEVER apply this bundle to the production Supabase project.
// Production must use only supabase-migrations/archive/ + supabase-migrations/.
// ============================================================================

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const ARCHIVE_DIR = path.join(ROOT, 'supabase-migrations', 'archive');
const PARENT_DIR = path.join(ROOT, 'supabase-migrations');
const OUT_PATH = path.join(ROOT, 'scripts', 'test-bootstrap.sql');

const MIGRATION_RX = /^(\d{3})_.+\.sql$/;

function listMigrations(dir) {
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isFile() && MIGRATION_RX.test(d.name))
    .map((d) => d.name)
    .sort();
}

function banner(label) {
  const bar = '-- ' + '='.repeat(76);
  return `\n\n${bar}\n-- ${label}\n${bar}\n\n`;
}

const archived = listMigrations(ARCHIVE_DIR);
const parent = listMigrations(PARENT_DIR);

if (archived.length === 0 && parent.length === 0) {
  console.error('No migration files found. Aborting.');
  process.exit(1);
}

let out = `-- ============================================================================
-- WCF Planner test-project bootstrap (generated)
-- ============================================================================
-- Generated by scripts/build_test_bootstrap.js. DO NOT EDIT BY HAND — re-run
-- the generator instead. This file concatenates a profiles seed + every
-- production migration (001-029) + a TEST-PROJECT-ONLY exec_sql function
-- used by Playwright reset helpers.
--
-- WARNING: NEVER apply this file to the production Supabase project. The
-- exec_sql function below grants service_role unrestricted SQL execution
-- which is acceptable in an isolated test project but unacceptable in
-- production. Production uses only supabase-migrations/ + archive/ files.
--
-- Migration count: ${archived.length} archived (001-${archived.at(-1)?.match(MIGRATION_RX)?.[1]}) + ${parent.length} new (${parent[0]?.match(MIGRATION_RX)?.[1]}-${parent.at(-1)?.match(MIGRATION_RX)?.[1]}).
-- Generated: ${new Date().toISOString()}
-- ============================================================================
`;

out += banner('hand_created_tables_seed.sql — TEST PROJECT ONLY');
out += `-- Nine tables in the production schema were created by hand (in the
-- Supabase Dashboard or via Supabase auth templates) before any migration
-- in this repo was written. They live in production but no .sql file
-- creates them. To replay the bundle on a fresh test project, recreate the
-- same shapes here so every migration that ALTERs / UPDATEs / references
-- them (e.g. mig 008 ALTER profiles, mig 011 UPDATE webform_config) can
-- apply cleanly on top.
--
-- Schemas captured 2026-04-27 from production via information_schema.
-- columns (read-only). Type-faithful, default-faithful. Constraints (FK,
-- CHECK) inferred from app behavior — kept conservative so migrations
-- 008/016 can extend them without conflicts.
--
-- Intentionally NO RLS policies. Tests use service_role (bypasses RLS).
-- The dev app's authenticated session works without policies for the smoke
-- flow. Add policies later if a spec needs to verify anon/authenticated
-- access patterns or test write-side RLS.

-- profiles ----------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text default 'farm_team',
  created_at timestamptz default now(),
  program_access text[]
);

-- app_store ---------------------------------------------------------------
create table if not exists public.app_store (
  key text primary key,
  data jsonb,
  updated_at timestamptz default now()
);

-- webform_config ----------------------------------------------------------
create table if not exists public.webform_config (
  key text primary key,
  data jsonb
);

-- poultry_dailys ----------------------------------------------------------
create table if not exists public.poultry_dailys (
  id text primary key,
  submitted_at timestamptz default now(),
  date text,
  team_member text,
  batch_id text,
  batch_label text,
  feed_type text,
  feed_lbs numeric,
  grit_lbs numeric,
  group_moved boolean,
  waterer_checked boolean,
  mortality_count integer default 0,
  mortality_reason text,
  comments text,
  source text
);

-- layer_dailys ------------------------------------------------------------
create table if not exists public.layer_dailys (
  id text primary key,
  submitted_at timestamptz default now(),
  date text,
  team_member text,
  batch_id text,
  batch_label text,
  feed_type text,
  feed_lbs numeric default 0,
  grit_lbs numeric default 0,
  layer_count integer,
  group_moved boolean,
  waterer_checked boolean,
  mortality_count integer default 0,
  mortality_reason text,
  comments text,
  source text
);

-- egg_dailys --------------------------------------------------------------
create table if not exists public.egg_dailys (
  id text primary key,
  submitted_at timestamptz default now(),
  date text,
  team_member text,
  group1_id text,
  group1_name text,
  group1_count integer,
  group2_id text,
  group2_name text,
  group2_count integer,
  group3_id text,
  group3_name text,
  group3_count integer,
  group4_id text,
  group4_name text,
  group4_count integer,
  daily_dozen_count numeric,
  dozens_on_hand numeric,
  comments text
);

-- pig_dailys (note: no feed_type column, no comments — uses 'issues') -----
create table if not exists public.pig_dailys (
  id text primary key,
  submitted_at timestamptz default now(),
  date text not null,
  team_member text,
  batch_id text not null,
  batch_label text,
  pig_count integer,
  feed_lbs numeric,
  group_moved boolean default true,
  nipple_drinker_moved boolean default true,
  nipple_drinker_working boolean default true,
  troughs_moved boolean default true,
  fence_walked boolean default true,
  fence_voltage numeric,
  issues text,
  source text
);

-- layer_batches -----------------------------------------------------------
create table if not exists public.layer_batches (
  id text primary key,
  name text not null,
  status text not null default 'active',
  arrival_date date,
  original_count integer,
  supplier text,
  cost_per_bird numeric,
  brooder_name text,
  brooder_entry_date date,
  brooder_exit_date date,
  schooner_name text,
  schooner_entry_date date,
  schooner_exit_date date,
  notes text,
  created_at timestamptz default now(),
  per_lb_starter_cost numeric,
  per_lb_grower_cost numeric,
  per_lb_layer_cost numeric
);

-- layer_housings ----------------------------------------------------------
create table if not exists public.layer_housings (
  id text primary key,
  batch_id text not null,
  housing_name text not null,
  status text not null default 'active',
  allocated_count integer,
  current_count integer,
  start_date date,
  retired_date date,
  notes text,
  created_at timestamptz default now(),
  current_count_date date
);
`;

for (const file of archived) {
  out += banner(`archive/${file}`);
  out += fs.readFileSync(path.join(ARCHIVE_DIR, file), 'utf8').replace(/\r\n/g, '\n');
}

for (const file of parent) {
  out += banner(file);
  out += fs.readFileSync(path.join(PARENT_DIR, file), 'utf8').replace(/\r\n/g, '\n');
}

out += banner('exec_sql.sql — TEST PROJECT ONLY — DO NOT APPLY TO PRODUCTION');
out += `-- public.exec_sql(text) is called by tests/setup/reset.js to TRUNCATE the
-- test-owned table whitelist before each spec. SECURITY DEFINER + revoked
-- from public/anon/authenticated means only service_role can execute it.
-- This is acceptable in an isolated test project. NEVER add this function
-- to the production database.
create or replace function public.exec_sql(sql text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  execute sql;
end;
$$;

revoke execute on function public.exec_sql(text) from public;
revoke execute on function public.exec_sql(text) from anon;
revoke execute on function public.exec_sql(text) from authenticated;
-- service_role retains EXECUTE by default.
`;

fs.writeFileSync(OUT_PATH, out, 'utf8');
const sizeKb = (out.length / 1024).toFixed(1);
console.log(
  `Wrote ${path.relative(ROOT, OUT_PATH)} (${archived.length + parent.length} migrations + exec_sql, ${sizeKb} KB).`
);
